import static java.lang.Math.sqrt; // import Math

public class DoingMathWithNumbersForm extends javax.swing.JFrame {

    /**
     * Creates new form DoingMathWithNumbersForm
     */
    public DoingMathWithNumbersForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btnSubtract = new javax.swing.JButton();
        btnDivde = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtUserName = new javax.swing.JTextField();
        txtNumber1 = new javax.swing.JTextField();
        txtNumber2 = new javax.swing.JTextField();
        lblResult = new javax.swing.JLabel();
        btnMin = new javax.swing.JButton();
        btnMax = new javax.swing.JButton();
        lblOperator = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel1.setText("User Name");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel2.setText("First Number");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel3.setText("Second Number");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel4.setText("Result");

        btnAdd.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnMultiply.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        btnMultiply.setText("Multiply");
        btnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplyActionPerformed(evt);
            }
        });

        btnSubtract.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        btnSubtract.setText("Subtract");
        btnSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtractActionPerformed(evt);
            }
        });

        btnDivde.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        btnDivde.setText("Divide");
        btnDivde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivdeActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        txtUserName.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        txtNumber1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        txtNumber2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        lblResult.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N

        btnMin.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        btnMin.setText("Min");
        btnMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinActionPerformed(evt);
            }
        });

        btnMax.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        btnMax.setText("Max");
        btnMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaxActionPerformed(evt);
            }
        });

        lblOperator.setText("--");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMultiply)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDivde))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSubtract)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(163, 163, 163)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblOperator, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(txtNumber1)
                            .addComponent(txtNumber2)
                            .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(63, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOperator, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnSubtract)
                    .addComponent(btnClear)
                    .addComponent(btnMin))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMultiply)
                    .addComponent(btnDivde)
                    .addComponent(btnExit)
                    .addComponent(btnMax))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplyActionPerformed
        /*Multiply*/
        // 1 :: Declare variables for project
        String strNumber1, strNumber2, strResult;
        int number1, number2, result;

        // 2 :: Get test form text box
        strNumber1 = txtNumber1.getText();
        strNumber2 = txtNumber2.getText();

        // 3 :: Covert from string to int
        number1 = Integer.parseInt(strNumber1);
        number2 = Integer.parseInt(strNumber2);

        // 4 :: Calculate the product & store in result
        result = number1 * number2;

        // 5 :: convert result into string & store it in strResult
        strResult = String.format("%s", result);

        // 6 :: Print strResult with lblResult
        lblResult.setText(strResult);

        // 7 :: show the user the operator type 
        lblOperator.setText("Multiplication");
        
    }//GEN-LAST:event_btnMultiplyActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        /*Addition*/
        // 1 :: Declare variables for project
        String strNumber1, strNumber2, strResult;
        int number1, number2, result;

        // 2 :: Get test form text box
        strNumber1 = txtNumber1.getText();
        strNumber2 = txtNumber2.getText();

        // 3 :: Covert from string to int
        number1 = Integer.parseInt(strNumber1);
        number2 = Integer.parseInt(strNumber2);

        // 4 :: Calculate the sum & store in result
        result = number1 + number2;

        // 5 :: convert result into string & store it in strResult
        strResult = String.format("%s", result);

        // 6 :: Print strResult with lblResult
        lblResult.setText(strResult);

        // 7 :: show the user the operator type 
        lblOperator.setText("Addition");

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // exit the program
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtractActionPerformed
        /*Min*/
        // 1 :: Declare variables for project
        String strNumber1, strNumber2, strResult;
        int number1, number2, result;

        // 2 :: Get text from text box
        strNumber1 = txtNumber1.getText();
        strNumber2 = txtNumber2.getText();

        // 3 :: Covert from string to int
        number1 = Integer.parseInt(strNumber1);
        number2 = Integer.parseInt(strNumber2);

        // 4 :: Calculate the Difference & store in result
        result = number1 - number2;

        // 5 :: convert result into string & store it in strResult
        strResult = String.format("%s", result);

        // 6 :: Print strResult with lblResult
        lblResult.setText(strResult);

        // side: show the user the operator type
        lblOperator.setText("Subtraction");

    }//GEN-LAST:event_btnSubtractActionPerformed

    private void btnDivdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivdeActionPerformed
        /*Division*/
        // 1 :: Declare variables for project
        String strNumber1, strNumber2, strResult;
        int number1, number2, result;

        // 2 :: Get test form text box
        strNumber1 = txtNumber1.getText();
        strNumber2 = txtNumber2.getText();

        // 3 :: Covert from string to int
        number1 = Integer.parseInt(strNumber1);
        number2 = Integer.parseInt(strNumber2);

        // 4 :: Calculate the Quotient & store in result
        result = number1 / number2;

        // 5 :: convert result into string & store it in strResult
        strResult = String.format("%s", result);

        // 6 :: Print strResult with lblResult
        lblResult.setText(strResult);

        // 7 :: show the user the operator type
        lblOperator.setText("Division");

    }//GEN-LAST:event_btnDivdeActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        /*Clear*/
        // Clear all parts of the form
        txtNumber1.setText("");
        txtNumber2.setText("");
        txtUserName.setText("");
        lblOperator.setText("");
        lblResult.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinActionPerformed
        // 1 :: Declare variables for project
        String strNumber1, strNumber2, strResult;
        int number1, number2, minNumber;

        // 2 :: Get test form text box
        strNumber1 = txtNumber1.getText();
        strNumber2 = txtNumber2.getText();

        // 3 :: Covert from string to int
        number1 = Integer.parseInt(strNumber1);
        number2 = Integer.parseInt(strNumber2);

        // 4 :: Calculate the Quotient & store in result
        minNumber = Math.min(number1, number2);

        // 5 :: convert result into string & store it in strResult
        strResult = String.format("%s", minNumber);

        // 6 :: Print strResult with lblResult
        lblResult.setText(strResult);

        // 7 :: show the user the operator type
        lblOperator.setText("Min");

    }//GEN-LAST:event_btnMinActionPerformed

    private void btnMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaxActionPerformed
        /*Max*/
        // 1 :: Declare variables for project
        String strNumber1, strNumber2, strResult;
        int number1, number2, maxNumber;

        // 2 :: Get test form text box
        strNumber1 = txtNumber1.getText();
        strNumber2 = txtNumber2.getText();

        // 3 :: Covert from string to int
        number1 = Integer.parseInt(strNumber1);
        number2 = Integer.parseInt(strNumber2);

        // 4 :: Calculate the Difference & store in result
        maxNumber = Math.max(number1, number2);

        // 5 :: convert result into string & store it in strResult
        strResult = String.format("%s", maxNumber);

        // 6 :: Print strResult with lblResult
        lblResult.setText(strResult);

        // 7 :: show the user they are using Max
        lblOperator.setText("Max");

    }//GEN-LAST:event_btnMaxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoingMathWithNumbersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoingMathWithNumbersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoingMathWithNumbersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoingMathWithNumbersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoingMathWithNumbersForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDivde;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnMax;
    private javax.swing.JButton btnMin;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnSubtract;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblOperator;
    private javax.swing.JLabel lblResult;
    private javax.swing.JTextField txtNumber1;
    private javax.swing.JTextField txtNumber2;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
