/**
 * Project Name: Show & Hide a Picture in Java
 * Programmer: Student - Christian Alvarez
 * Date: 02-08-2021
 */
public class ShowHideForm extends javax.swing.JFrame {

    public ShowHideForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBull = new javax.swing.JLabel();
        btnHideImage = new javax.swing.JButton();
        btnShowImage = new javax.swing.JButton();
        lblBlackhawk = new javax.swing.JLabel();
        lblWhitesock = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 153));

        lblBull.setIcon(new javax.swing.ImageIcon("C:\\Users\\chris\\Downloads\\Bulls-Neon.jpg")); // NOI18N
        lblBull.setText("jLabel1");

        btnHideImage.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnHideImage.setText("Hide Picture");
        btnHideImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHideImageActionPerformed(evt);
            }
        });

        btnShowImage.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnShowImage.setText("Show Picture");
        btnShowImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowImageActionPerformed(evt);
            }
        });

        lblBlackhawk.setIcon(new javax.swing.ImageIcon("C:\\Users\\chris\\Downloads\\BlackhawksT.png")); // NOI18N
        lblBlackhawk.setText("jLabel1");

        lblWhitesock.setIcon(new javax.swing.ImageIcon("C:\\Users\\chris\\Downloads\\Chicago_White_Sox.png")); // NOI18N
        lblWhitesock.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHideImage)
                        .addGap(95, 95, 95)
                        .addComponent(btnShowImage))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBull, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(lblBlackhawk, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addComponent(lblWhitesock, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBull)
                    .addComponent(lblBlackhawk)
                    .addComponent(lblWhitesock))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHideImage)
                    .addComponent(btnShowImage))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHideImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHideImageActionPerformed
        // 1 :: Hide Images
        lblBull.setVisible(false);
        lblBlackhawk.setVisible(false);
        lblWhitesock.setVisible(false);
    }//GEN-LAST:event_btnHideImageActionPerformed

    private void btnShowImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowImageActionPerformed
        // 2 :: Show Image
        lblBull.setVisible(true);
        lblBlackhawk.setVisible(true);
        lblWhitesock.setVisible(true);
    }//GEN-LAST:event_btnShowImageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowHideForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowHideForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowHideForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowHideForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowHideForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHideImage;
    private javax.swing.JButton btnShowImage;
    private javax.swing.JLabel lblBlackhawk;
    private javax.swing.JLabel lblBull;
    private javax.swing.JLabel lblWhitesock;
    // End of variables declaration//GEN-END:variables
}
